spring:
  application:
  name: spring-log-demo
logging:
  level:
    root: info
    com:
      cya:
        springlogdemo:
          controller: trace
          service: error

  file:
    name: log/log.log
#    path: logger/log.log
  logback:
    rollingpolicy:
      max-file-size: 1KB
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i
